/**
 * What each block of the explicit-control evaluator does, in a sentence, for
 * the caption when control enters it (§5.4).
 */
export const EVALUATOR_BLOCKS: Readonly<Record<string, string>> = {
  read_evaluate_print_loop: 'Read the next program, scan out its declarations and evaluate it in the program environment.',
  print_result: 'The value is in `val`: print the stack statistics and the value, then read again.',
  eval_dispatch: 'Dispatch on the kind of component in `comp`.',
  ev_literal: 'A literal: its value goes straight into `val`.',
  ev_name: 'A name: look up its value in `env`.',
  ev_lambda: 'A lambda expression: make a function from its parameters, body and `env`.',
  ev_conditional: 'A conditional: save `comp`, `env` and `continue`, then evaluate the predicate.',
  ev_conditional_decide: 'The predicate’s value is in `val`: restore what was saved and choose a branch.',
  ev_conditional_consequent: 'Evaluate the consequent, in tail position.',
  ev_conditional_alternative: 'Evaluate the alternative, in tail position.',
  ev_sequence: 'A sequence: save `continue` and start on the statements.',
  ev_sequence_next: 'Evaluate the next statement of the sequence.',
  ev_sequence_continue: 'Back from a statement: restore `env` and the remaining statements.',
  ev_sequence_last_statement: 'The last statement: restore `continue` and evaluate it in tail position.',
  ev_sequence_empty: 'An empty sequence has the value `undefined`.',
  ev_operator_combination: 'An operator combination: rewrite it as an application of the operator’s function.',
  ev_application: 'An application: save `continue`, `env` and the argument expressions, then evaluate the function expression.',
  ev_appl_did_function_expression: 'The function is in `val`: move it to `fun` and start on the arguments.',
  ev_appl_argument_expression_loop: 'Save `argl` and evaluate the next argument expression.',
  ev_appl_accumulate_arg: 'Back from an argument: add its value to `argl`.',
  ev_appl_last_arg: 'The last argument expression: evaluate it without saving `env` or `unev`.',
  ev_appl_accum_last_arg: 'Add the last value to `argl`, restore `fun`, and apply.',
  apply_dispatch: 'Every argument is in `argl`: decide what kind of function is in `fun`.',
  primitive_apply: 'A primitive function: apply it to `argl`, restore `continue` and return.',
  compound_apply: 'A compound function: extend its environment with the arguments, mark the stack, and evaluate its body.',
  compiled_apply: 'A compiled function: mark the stack and jump to its entry point.',
  ev_return: 'A return statement: revert the stack to the function’s mark, restore `continue`, and evaluate the return expression in tail position.',
  return_undefined: 'The body ended without a return: revert the stack and return `undefined`.',
  ev_block: 'A block: extend `env` with its declared names, unassigned, and evaluate the body.',
  ev_assignment: 'An assignment: save the name, `env` and `continue`, then evaluate the new value.',
  ev_assignment_install: 'Install the new value in the environment.',
  ev_function_declaration: 'A function declaration: treat it as a constant declaration of a lambda expression.',
  ev_declaration: 'A declaration: save the name, `env` and `continue`, then evaluate the value.',
  ev_declaration_assign: 'Bind the declared name to its value; the declaration’s own value is `undefined`.',
  external_entry: 'Compiled code: start it with the program environment, to return to `print_result`.',
  unknown_component_type: 'This kind of component is not one the evaluator knows.',
  unknown_function_type: 'The value in `fun` is not a function.',
  signal_error: 'Print the error and go back to reading.',
  evaluator_done: 'No more input: the evaluator stops.',
};
